version: "3"
services:
  web:
    restart: always
    container_name: restaurant
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
networks:
  network1:
